version: '3.8'

services:
  terminal-turtle:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=8080
      - WORKING_DIRECTORY=/data/workspace
      - AGENT_NAME=${AGENT_NAME:-terminal-turtle}
      - AGENT_ID=${AGENT_ID}
      - API_KEY=${API_KEY}
      # Ngrok configuration
      - ENABLE_NGROK=${ENABLE_NGROK:-false}
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    volumes:
      # Persistent workspace for file operations
      - ./workspace:/data/workspace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.singularitybridge.description=TerminalTurtle - Developer-friendly terminal automation tool"
      - "com.singularitybridge.repository=https://github.com/singularitybridge/TerminalTurtle"
