version: '3.8'

services:
  devatelier:
    build: .
    ports:
      - "8080:8080"                              # API server
      - "${DEV_SERVER_PORT:-3100}:3100"          # Next.js/React dev server
      - "${NODE_APP_PORT:-4100}:4100"            # Node.js app port
      - "${VITE_PORT:-5273}:5173"                # Vite dev server
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=8080
      - WORKING_DIRECTORY=/data/workspace
      - AGENT_NAME=${AGENT_NAME:-devatelier}
      - AGENT_ID=${AGENT_ID}
      - API_KEY=${API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEV_SERVER_PORT=${DEV_SERVER_PORT:-3100}
      - NODE_APP_PORT=${NODE_APP_PORT:-4100}
      - VITE_PORT=${VITE_PORT:-5273}
      - AUTO_START_DEV_SERVER=${AUTO_START_DEV_SERVER:-false}
    volumes:
      - ./workspace:/data/workspace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.devatelier.description=AI-powered development workspace"
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
